apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwsx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwsx
  template:
    metadata:
      labels:
        app: qwsx
    spec:
      containers:
      - image: okteto.dev/qwsx:latest
        name: qwsx
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e55f8e49-f361-47e2-ad1d-8b3c6a41fecc"
        - name: Vless_Path
          value: "/eythrfsaajyu"
        - name: Vmess_UUID
          value: "e55f8e49-f361-47e2-ad1d-8b3c6a41fecc"
        - name: Vmess_Path
          value: "/fsdffvbbgu"
        - name: Share_Path
          value: "/v2link"
